apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for devhub-mad
spec:
  type: url
  targets:
    - scaffolder-templates/frontend/template.yaml
    - scaffolder-templates/spring-backend/template.yaml
    - scaffolder-templates/quarkus-backend/template.yaml
    - scaffolder-templates/gateway/template.yaml
    - scaffolder-templates/ephemeral-cluster-medium/template.yaml
    - scaffolder-templates/operator_instance_jaeger/template.yaml 
    - scaffolder-templates/namespace-medium/template.yaml 
    - scaffolder-templates/operator_instance_mongodb/template.yaml     
    - scaffolder-templates/operator_instance_mesh/template.yaml 
    - scaffolder-templates/rhel9-vm-medium/template.yaml  